### ISSUE TITLE
Interpretation of the MK/platelet component

### ISSUE THREAD

**Issue by andrewram4287** [meyer-lab/scCP#317]
For component that picks out platelet/MK related genes, which subset of cells are being picked out? Not a processing batch/pool issue, when investigating the raw data for mean expression of these genes picked out, no apparent difference is found in disease status, even when "gated out" most highly weighted cells for this component.

**Comment by aarmey** [comment]
One thought—it might help to look at the actual raw data (in X.raw in the AnnData object) rather than the batch corrected data. If this signal differs by processing batch like the authors suggested, then this might explain why you don't see an obvious trend in your plots. Pf2 could still be picking up this signal because batch correction is never perfect.
